title: Intex pool filtration controller for ESPHome
description: |
  This is custom firmware based on ESPHome, which allows you to control certain Intex pool
  filtration pumps and saltwater chlorinators with an ESP32 microcontroller.
theme: jekyll-theme-slate
