name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'static/**'
      - '.github/workflows/publish-pages.yml'
      - '.github/workflows/publish-firmware.yml'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'static/**'
      - '.github/workflows/publish-pages.yml'
      - '.github/workflows/publish-firmware.yml'
      - 'README.md'
      - '.vscode/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        #### Modify below here to match your project ####
        file:
          - pump-controller
        #### Modify above here to match your project ####

        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v6.0.0
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}
      - name: ESPHome ${{ matrix.esphome-version }} Factory
        uses: esphome/build-action@v6.0.0
        with:
          yaml-file: ${{ matrix.file }}.factory.yaml
          version: ${{ matrix.esphome-version }}

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2

      - name: Build Tests
        uses: threeal/cmake-action@v2.1.0

      - name: Run Tests
        uses: threeal/ctest-action@v1.1.0
        with:
          args: --output-junit test-results.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results.xml
